### ISSUE TITLE
Question : Adding Subtitles

### ISSUE THREAD

**Issue by D3dou** [DolbyLaboratories/dlb_mp4base#10]
Hello,

this program works great !

I'm wondering if it's possible to add an implementation for subtitles management into the final .mp4 file ?

If it's not, is there another program that would do the trick without any quality loss ?

Thanks in advance.

Regards.

**Comment by ShaoWeiguo** [comment]
Hi,

There is no plan to support subtitles.  

Maybe you can have a try with Bento4.

**Comment by Grencola** [comment]
try this: https://bit.ly/2OYwutN and no, it's not malware, I just used mp4muxer plus a few other tools to simplify the process :)

**Comment by ShaoWeiguo** [comment]
Now another optional is Bento4, https://github.com/DolbyLaboratories/Bento4.
