### ISSUE TITLE
Perhaps add profiles in documentation?

### ISSUE THREAD

**Issue by cgorlla** [DolbyLaboratories/dlb_mp4base#11]
#8 is still open for some reason, related issue.

It may be pertinent to add listing of profiles in the readme documentation. e.g

Dolby Vision
bitstream
profile ID
BL signal
crosscompatibility
ID
Dolby Vision
bitstream
profile string
BL/EL codec BL:EL Video usability
information (VUI)
4 2 dvhe.04 10-bit HEVC 1:¼ • Base layer:
1, 1, 1,0,0
• Enhancement
layer:
2,2,2,1,0
5 0 dvhe.05 10-bit HEVC N/A Base layer:
2,2,2,1,0
7 6 dvhe.07 10-bit HEVC 1:¼ for UHD • Base layer:
16,9,9,0,2
• Enhancement
layer:
16,9,9,0,2
1:1 for FHD • Base layer:
16,9,9,0,2
• Enhancement
layer:
16,9,9,0,2
8 1 hev1.08 10-bit HEVC N/A Base layer:
16,9,9,0,0
8 2 hev1.08 10-bit HEVC N/A Base layer:
1, 1, 1,0,0
9 2 avc3.09 8-bit AVC N/A Base layer:
1, 1, 1,0,0

**Comment by ShaoWeiguo** [comment]
Please see #8
