### ISSUE TITLE
Request for Windows x64 executable binary

### ISSUE THREAD

**Issue by kangstarr** [DolbyLaboratories/dlb_mp4base#13]
The prebuilt mp4muxer.exe for Windows won't run on Windows 10 64-bit architecture because the app is 16-bit? Can you upgrade to 64-bit architecture? Below is the error that pops up.

Pop-up error message
Unsupported 16-Bit Application
The program or feature "\??\C:\tools\mp4muxer\mp4muxer.exe" canot start or run due to incompatibility with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available."

Command-line error message
This version of C:\tools\mp4muxer\mp4muxer.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by ShaoWeiguo** [comment]
It works on my side, Microsoft Windows [Version 10.0.17134.1365].  Maybe you could build the executable file by yourself.

**Comment by kangstarr** [comment]
I did end up building it myself and it worked.

FYI I'm running Win 10 Pro (build 1909)

Thanks,
./steven
