### ISSUE TITLE
MUX OCCURS, BUT FILE SIZE IS 0KB

### ISSUE THREAD

**Issue by filmjamie** [DolbyLaboratories/dlb_mp4base#16]
Hi, I followed the process and when I muxed my .h264 with my .ec3, the resulting .mp4 file is 0KB.  This is an 8K 3D 360 video, which is approximately 8GB.  8192x8192 are the dimensions.  I'm wondering if the video resolution is beyond what is currently supported?

Thank You!  

![SORTA_KINDA](https://user-images.githubusercontent.com/23222948/92691952-4d3ee480-f2f8-11ea-9cba-09d8b1a29102.PNG)

**Comment by filmjamie** [comment]
What does "can handle the level" mean?  Does that mean that it CAN'T handle this glorious 8K 3D 360 video format?!  I HAVE TO KNOW!!!

**Comment by ShaoWeiguo** [comment]
@filmjamie Yes, it means "can **NOT** handle the level". Sorry for the typo.

**Comment by filmjamie** [comment]
All good @ShaoWeiguo, I discovered a few workarounds and my 8K 3D 360/VR Atmos workflow is SUCCESSFUL!  Thanks for following up and please let me know if you'd like any help testing new 8K+ tools as you develop them!

All the best, 

James Markham Hall, Jr.
Gold Creek VR

**Comment by ShaoWeiguo** [comment]
I have fixed the typo.
