### ISSUE TITLE
Authoring HEVC files with hvc1 codec ID

### ISSUE THREAD

**Issue by kdcloudy** [DolbyLaboratories/dlb_mp4base#21]
Muxing any h265 elementary streams results in the final output track to have a codec ID of hev1 and not hvc1

This goes against Apple's HLS and QuickTime spec, and hence the final file doesn't play in QuickTime.

(I am trying to mux an HDR10 HEVC file with it's Atmos track)

**Comment by HongyuS** [comment]
Please check my fork! I followed yusesope's advice to force Apple QuickTime compatibility. It works fine for me. You are welcomed to have a try!

https://github.com/HongyuS/dlb_mp4base

**Comment by kdcloudy** [comment]
Thanks for the tip! I'll be sure to make use of it

**Comment by ShaoWeiguo** [comment]
It has been fixed in v1.1.0.

**Comment by kdcloudy** [comment]
Thanks @ShaoWeiguo

**Comment by ShaoWeiguo** [comment]
fixed.
