### ISSUE TITLE
dvh1flag doesn't work

### ISSUE THREAD

**Issue by perrinpagess** [DolbyLaboratories/dlb_mp4base#23]
using the option --dvh1flag returns an error on mp4muxer 1.1.0 saying the option doesn't exist, even though it's in the help dialogue.

` --dvh1flag                         = Set the elementray stream index to set HEVC track's sample entry name to 'dvh1',
                                      default sample entry box name is 'dvhe' for non-cross compatible stream.`

`Error parsing command line: Unknown option: --dvh1flag
Error parsing command line!`

**Comment by XingzhaoYun** [comment]
Are you using the binaries directly from bin folder? could you provide the whole command line? I haven’t seen any issue on my side.

**Comment by perrinpagess** [comment]
I'm on windows 11 stable using the build from the bin folder. Maybe I'm using the flag wrong? The video is 15 Mbps profile 5 level 6 and the audio is 5.1 eac3 768kbps.

`mp4muxer -o "output.mp4" --dv-profile 5 -i "video.hevc" -i "audio.ec3" --media-lang eng --dvh1flag`

**Comment by M0djO** [comment]
I think you're missing the index you need to provide with the --dvh1flag option, to my understanding this needs to be the index of the hevc track, so i your case i assume it would be 0

try;

`mp4muxer -o "output.mp4" --dv-profile 5 -i "video.hevc" -i "audio.ec3" --media-lang eng --dvh1flag 0`

**Comment by perrinpagess** [comment]
@M0djO that resolved the issue, thanks!
