### ISSUE TITLE
mp4muxer Gives Audio Stream Incorrect Header

### ISSUE THREAD

**Issue by perrinpagess** [DolbyLaboratories/dlb_mp4base#24]
When using this test file:

http://media.developer.dolby.com/DolbyVision_Atmos/mp4/iOS_P5_GlassBlowing2_3840x2160%4059.94fps_15200kbps.mp4

The untouched file's metadata is:

`Stream #0:0[0x1](und): Video: hevc (Main 10) (dvh1 / 0x31687664), yuv420p10le(pc), 3840x2160 [SAR 1:1 DAR 16:9], 15184 kb/s, 59.94 fps, 59.94 tbr, 60k tbn (default)`

`Stream #0:1[0x2](und): Audio: eac3 (ec-3 / 0x332D6365), 48000 Hz, 5.1(side), fltp, 640 kb/s (default)`

My mp4muxer command:

`mp4muxer -o output.mp4 -i input.hevc -i input.ec3 --dv-profile 5`

After using ffmpeg or mp4demuxer to demux and mp4muxer to remux:

`Stream #0:0[0x1](und): Video: hevc (Main 10) (dvhe / 0x65687664), yuv420p10le(pc), 3840x2160 [SAR 1:1 DAR 16:9], 15185 kb/s, 59.94 fps, 59.94 tbr, 60k tbn (default)`

`Stream #0:1[0x2](und): Audio: none (dvhe / 0x65687664), 48000 Hz, 5.1(side), 640 kb/s (default)`

The resulting file after using mp4muxer has audio that is unplayable because of the incorrect header.

**Comment by bpandel** [comment]
I have the exact same issue. File can be played fine when I skip the audio track, otherwise players don't recognize dvhe audio codec.

**Comment by perrinpagess** [comment]
Any update on this? Is there something wrong with my command? An mp4 muxer that doesn't mux audio correctly is fairly useless.

**Comment by XingzhaoYun** [comment]
Have you got any chance to test the latest binary?

**Comment by M0djO** [comment]
Didn't have notifications configured properly so didn't notice there was a new binary. I will try with my files when I get home tonight.

**Comment by M0djO** [comment]
As far as I am able to tell the latest binary fixes the issue for me. 
The Codec ID field in MediaInfo now shows ec-3 instead of dvhe and my player recognizes the file and plays it back.

**Comment by perrinpagess** [comment]
New build fixed the issue, thanks!
