### ISSUE TITLE
Black screen on iOS/ATV even dvh1flag

### ISSUE THREAD

**Issue by sw5163** [DolbyLaboratories/dlb_mp4base#28]
When converting dvhe->dvh1, mp4muxer leads to black screen on iOS/ATV.
File produced by mp4box and mp4mux(bento4) will be fine.
Someone send me this:
```
'hvc1' stores all parameter sets inside the MP4 container below the sample description boxes. 
'hev1' stores all parameter sets in band (inside the HEVC stream).

The parameter sets are essentially mandatory metadata necessary to decode the streams.

So you have two slightly different ways of muxing HEVC into MP4.

I'd choose based on the play out and transport scenario.

Your player or your transport specification may require one or the other.
```

**Comment by XingzhaoYun** [comment]
Could you help provide the details of how to convert?

**Comment by sw5163** [comment]
Dolby's [official demo](http://media.developer.dolby.com/DolbyVision_Atmos/mp4/iOS_P5_GlassBlowing2_3840x2160%4059.94fps_15200kbps.mp4) can directly play on iOS internal player.

`ffmpeg -i video.mp4 -c copy dv.hevc` to extract

`mp4muxer -i dv.hevc --dv-profile 5 --dvh1flag 0` black screen on iOS/ATV.

`mp4box -add dv.hevc -new p5.dvh1.mp4` play as normal.

`mp4mux(bento4) --track dv.hevc#dv_profile=5,frame_rate=59.94` play as normal.

But I'm really not good at programming, sorry.

**Comment by sw5163** [comment]
It turns out Apple can retrieve the information needed to initialize the decoder even if the file is wrongly muxed.
But it requires powerful processor.
So on newer iPhone/Mac/ATV playback will not have the black screen problem.
