### ISSUE TITLE
Changing HDR metadata

### ISSUE THREAD

**Issue by micsic85** [DolbyLaboratories/dlb_mp4base#3]
Is it possible to have a script to change the HDR metadata? 
Something like this:
-colorprim bt2020 -transfer smpte-st-2084 -colormatrix bt2020nc -masterdisplay G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50) -maxcll 0,0
NVHSP can do this for HDR10, but it doesnt work for this.

Thanks!

**Comment by ShaoWeiguo** [comment]
No, and there is no plan to add this feature.
This tool is used to multiplex the elementary stream (like AVC, HEVC and DD+ et al.) into MP4 container, and modify/patch the elementary stream is not in the scope.

**Comment by micsic85** [comment]
What future projects you have in work?
Converting those dual layers to a single layer DV would be perfect!
Thanks for your answer

**Comment by ShaoWeiguo** [comment]
Support more Dolby Vision profiles and av1 codecs are in the list.
"Converting those dual layers to a single layer DV would be perfect!", what's the meaning? Could you give more information?

**Comment by micsic85** [comment]
I mean a way to re-encode to a single layer (video) .
Because now it is 2 videos in the MP4 container (the HDR video + the DV layer)
But it could be great if we could encode this into one single layer, like the LG demos.

**Comment by micsic85** [comment]
For example Amazon fire stick TV only support profiles 5, 8 and 9 and they are all single layer

**Comment by ShaoWeiguo** [comment]
I see.  
But the tool doesn't support. 
The recommend method is to encode from the source file.

**Comment by micsic85** [comment]
but then Dolby Vision is lost
I need a way to encode but keeping dolby vision

**Comment by ShaoWeiguo** [comment]
I mean you need the **Dolby Vision Encoder** and **original** source file.

**Comment by micsic85** [comment]
from a dual layer DV file
It is easy to encode HDR10 content, but I still cannot manage to encode DV content
Because some TVs and players dont play dual layer DV files
Even using "mp4muxer --dv-profile 5 ..........." it is still dv profile 7

**Comment by ShaoWeiguo** [comment]
Sorry, there is no transocder for Dolby Vision.

**Comment by ValZapod** [comment]
> Even using "mp4muxer --dv-profile 5 ..........." it is still dv profile 7

profile 8. Or just buy LG C9, not some 💩 like LG CX that removed FEL support (at least they added back MEL, but not FEL).
