### ISSUE TITLE
SC miss-match

### ISSUE THREAD

**Issue by jakeycrx** [DolbyLaboratories/dlb_mp4base#6]
Hi

When I run the command line I get the error "sc miss-match" 

Do you have any idea what may be causing this?

**Comment by ShaoWeiguo** [comment]
"sc miss-match" means can't find the start code for HEVC stream.

**Comment by jakeycrx** [comment]
Thank you for your reply.

What is the best way to extract the 2 streams in HEVC format from the M2TS file?

**Comment by ShaoWeiguo** [comment]
2 HEVC elemental streams in M2TS container?

**Comment by jakeycrx** [comment]
Yes.  I have the 4k stream and the DV stream in the same M2TS file.

I used MKVtoolnix to extract them and saved them with a hevc file extension and I guess this is why it doesn't work.

**Comment by jakeycrx** [comment]
https://imgur.com/a/R0MnX28

**Comment by ShaoWeiguo** [comment]
Understand. I am not familiar with MKVtoolnix, sorry. We usually use Manzanita analyzer, but it need licensed. Maybe you can have a try with ffmpeg, not sure.

**Comment by jakeycrx** [comment]
OK.  Thank you for your help.

**Comment by jakeycrx** [comment]
Which file formats does it support?  Do the video files have to have a hevc extension?

**Comment by ShaoWeiguo** [comment]
It supports H264, H265, AC3, EC3, and AC4, and must be the elementary stream.

**Comment by sajttt** [comment]
eAC3to (latest) is perfect for demuxing

**Comment by farcry5** [comment]
mp4muxer -o output.mp4 -i audio.ac4 -i video_256kbps.h264 --mpeg4-comp-brand mp42,iso6,isom,msdh,dby1  , when i run this command its showing "ss mismatch" video file is h264 file
